# Generated by Django 4.2.2 on 2023-10-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyqs', '0005_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='usermail',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
