# Generated by Django 4.2.2 on 2023-10-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyqs', '0006_upload_usermail'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='sub_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
